# CMaNGOS TBC restarter configuration
INSTALL_PATH=/home/matuph/wow-emu/wow-tbc
AUTH_PATH=/home/matuph/wow-emu/wow-tbc/bin
WORLD_PATH=/home/matuph/wow-emu/wow-tbc/bin
LOG_PATH=/home/matuph/wow-emu/wow-tbc/logs/restarter

AUTH_BINARY=realmd
WORLD_BINARY=mangosd
AUTH_SESSION=tbc-realmd
WORLD_SESSION=tbc-mangosd

RESTART_DELAY=5
SHUTDOWN_WAIT=30
DEBUG_WITH_GDB=false
